name: Terraform Apply (Controlled)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to apply?"
        type: choice
        required: true
        options:
          - dev
          - stage
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    concurrency:
      group: terraform-apply-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Guard - only main can deploy to stage/prod
        if: ${{ inputs.environment != 'dev' && github.ref != 'refs/heads/main' }}
        run: |
          echo "Only main branch can deploy to stage/prod."
          exit 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Guard - ensure env vars exist
        shell: bash
        run: |
          test -n "${{ vars.AWS_REGION }}" || (echo "Missing AWS_REGION in this GitHub Environment" && exit 1)
          test -n "${{ vars.AWS_ROLE_ARN }}" || (echo "Missing AWS_ROLE_ARN in this GitHub Environment" && exit 1)

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Select workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform plan
        run: terraform plan -input=false -var-file="env/${{ inputs.environment }}.tfvars" -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false -lock-timeout=5m -auto-approve tfplan
